[package]
name = "jedda"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13.0"
rcgen = "0.8.14"
tokio = { version = "1.15.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.6.2"

[build-dependencies]
tonic-build = "0.6.2"
